version: '3.2'
services:
    db:
        image: postgres:latest
        container_name: sb_db # "Spring Boot 用のDB" という意味の任意の名前
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: 'dev' # DBのユーザー名（＝DB名）
            POSTGRES_PASSWORD: 'pass' # DBのパスワード
        volumes:
            - .\init_db:/docker-entrypoint-initdb.d
    java:
        build: .
        image: tiqwab/boot:0.0.1
        container_name: sb
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        tty: true
        depends_on:
            - db
